name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          command: buildozer -v android debug
          
